export type Layer = "sec" | "data" | "onto" | "logic" | "app" | "ops";

// 데이터 흐름 순서. 권한·보안과 운영은 모든 층에 걸치므로 마지막
export const layerLabels: Record<Layer, string> = {
  data: "데이터",
  onto: "온톨로지",
  logic: "로직",
  app: "앱",
  sec: "권한·보안",
  ops: "운영",
};

export interface Concept {
  id: string;
  /** 개념 목록 버튼과 개념 지도 상자에 쓰는 이름. 이 이름 하나만 고치면 목록·지도가 함께 바뀐다 */
  short: string;
  /** 지도 상자에서 이름을 여러 줄로 나눌 때만 지정. 이어 붙이면 short와 같아야 한다(빌드 시 검사) */
  mapLines?: string[];
  layer: Layer;
  title: string;
  lead: string;
  /** 개발자용 비유 (웹·DB 개념 기준) */
  analogy: string;
  /** 비개발자용 비유 (일상·업무 장면 기준) */
  everyday: string;
  points: string[];
  warn?: string;
  /** 공식 문서. 카드가 여러 기능을 함께 다루면(title이 "A · B") 기능마다 { label, href }로 나눠 같은 단계의 버튼으로 보여준다 */
  doc: string | { label: string; href: string }[];
  related: { label: string; href: string }[];
}

const D = "https://www.palantir.com/docs/foundry/";

// 모든 설명은 doc/related에 링크한 Palantir 공식 문서(osdk-ts 소스 포함)로 확인한 내용만 담는다
export const concepts: Concept[] = [
  {
    id: "dc", short: "Data Connection", layer: "data", title: "Data Connection",
    lead: "외부 시스템의 데이터를 Foundry로 가져오는(sync) 입구입니다. 반대로 webhook이나 data export로 외부 시스템에 다시 쓰는 연결도 만듭니다.",
    analogy: "외부 DB·SaaS에서 데이터를 가져오는 ETL의 추출(Extract) 단계에 해당합니다. Source는 접속 주소와 인증 정보를 담은 연결 설정이고 Sync는 그 연결로 실제 데이터를 가져오는 작업(지금은 batch sync 등)입니다.",
    everyday: "여러 거래처에서 오는 자료를 한곳에서 받아 두는 회사의 문서 수발실과 같습니다. 거래처별 연락처와 출입 방법(Source)을 등록해 두고 정해진 때마다 자료를 받아 옵니다(Sync).",
    points: [
      "Source: 외부 시스템 하나에 대한 연결입니다. 대상 위치(보통 URL)와 인증 정보를 담습니다.",
      "Sync는 데이터를 Foundry로 가져오는 작업을 통칭하던 예전 용어입니다. 지금은 batch, Iceberg, streaming, CDC, media sync 등 기능별 이름으로 나뉩니다.",
      "데이터는 외부에서 미리 가공하지 않고 원본 그대로(as-is) 가져오는 것을 원칙으로 합니다.",
      "실패 시 자동 재시도와 데이터 상태 모니터링을 기본으로 제공합니다.",
    ],
    warn: "Agent worker는 기존 고객을 위해 남겨 둔 레거시 방식입니다.",
    doc: D + "data-connection/overview",
    related: [{ label: "핵심 개념", href: D + "data-connection/core-concepts" }],
  },
  {
    id: "transform", short: "Python transform", layer: "data", title: "Python transform",
    lead: "입력 Dataset을 읽어 출력 Dataset을 쓰는 배치 코드입니다. Build가 실행될 때 동작합니다.",
    analogy: "API 핸들러가 아니라 cron 배치 잡에 가깝습니다. Code Repositories는 웹 IDE와 Git 저장소를 합친 도구입니다.",
    everyday: "매일 밤 정해진 시간에 재료를 한꺼번에 손질해 두는 주방의 밑준비와 같습니다. 주문이 들어올 때마다 요리하는 것이 아니라 미리 처리해 둔 결과를 다음 단계가 가져다 씁니다.",
    points: [
      "아래 엔진별 크기는 공식 문서가 대략적 기준(rule of thumb)으로 제시한 값이며 모든 쿼리에 들어맞지는 않습니다.",
      "pandas: 1GB·100만 행 미만 (데이터 크기는 압축 전 기준)",
      "Polars·DuckDB: 1~50GB, 2억 행까지",
      "PySpark: 50GB·2억 행 초과. 시작 오버헤드가 큽니다.",
      "Code Workspaces는 JupyterLab·RStudio·VS Code를 Foundry 안에서 쓰는 환경으로 transform과 모델도 만들 수 있습니다. 단일 노드에서 실행되므로 대규모 변환에는 Pipeline Builder나 Code Repositories를 권장합니다.",
    ],
    warn: "운영용 transform은 Polars를 기본으로 쓰도록 권장합니다. Spark는 대개 50GB를 넘고 filter pushdown 같은 최적화를 쓸 수 없을 때만 권장합니다.",
    doc: D + "transforms-python/compute-engines",
    related: [
      { label: "transform 기본", href: D + "transforms-python/transforms" },
      { label: "Code Workspaces", href: D + "code-workspaces/overview" },
      { label: "코드 도구 비교", href: D + "code-workbook/code-products-comparison" },
    ],
  },
  {
    id: "pb", short: "Pipeline Builder", layer: "data", title: "Pipeline Builder",
    lead: "클릭으로 파이프라인을 구성하는 도구입니다. 백엔드가 transform 코드를 생성하고 Build 전에 스키마를 검사합니다.",
    analogy: "Zapier나 n8n처럼 블록을 선으로 이어 흐름을 만드는 노코드 도구와 비슷합니다. 다만 이어 붙이는 블록이 필터·조인·그룹화 같은 SQL 연산이고 뒤에서 그 연산을 수행하는 transform 코드가 자동으로 만들어집니다.",
    everyday: "블록을 끼워 맞추듯 '거르기 → 합치기 → 묶기' 같은 단계를 화면에서 이어 붙이는 도구입니다. 단계를 다 이으면 그 작업을 실제로 수행하는 프로그램이 자동으로 만들어집니다.",
    points: [
      "Expression은 컬럼을 받아 컬럼 하나를 내고 Transform은 테이블 전체를 받아 테이블을 냅니다.",
      "실행 엔진으로 Spark와 Flink를 쓰며 DataFusion 기반의 Faster pipelines로 배치·증분 파이프라인을 더 빠르게 실행할 수 있습니다.",
      "출력 검사를 통과하지 못하면 Build를 막아 하류 파이프라인이 깨지는 것을 방지합니다.",
      "출력으로 Dataset, Object type·Link type, Stream, time series, 외부 내보내기를 지원합니다. Ontology에 바로 쓰는 direct datasource의 writer는 지금 Pipeline Builder뿐입니다.",
      "생성된 코드는 기존 Java transforms 저장소로만 내보낼 수 있습니다(PySpark 불가, 기본 배치 파이프라인만). 대상 브랜치의 기존 코드는 삭제되고 되돌릴 수 없는 단방향 작업입니다.",
      "UDF·LLM 호출·미디어 연산 등은 내보낸 코드에서 TODO로 남으며 결과가 원래 파이프라인과 다를 수 있습니다.",
    ],
    warn: "스트리밍 파이프라인은 모든 환경에서 제공되지는 않습니다. 필요하면 Palantir 담당자에게 문의합니다.",
    doc: D + "pipeline-builder/overview",
    related: [
      { label: "Expression과 Transform", href: D + "pipeline-builder/transforms-overview" },
      { label: "코드 내보내기", href: D + "pipeline-builder/export-pipeline" },
      { label: "Direct datasource", href: D + "object-indexing/direct-datasources" },
    ],
  },
  {
    id: "builds", short: "Builds · Schedules", layer: "data", title: "Builds · Schedules",
    lead: "Build는 transform·sync 같은 job을 실행해 출력을 새로 계산하는 작업이고 Schedule은 그 Build를 언제 실행할지 정합니다.",
    analogy: "CI의 빌드 잡과 cron 스케줄러를 합친 것과 같습니다. 코드를 커밋하면 실행 정의(JobSpec)가 갱신되고 트리거 조건이 맞으면 Build가 실행됩니다.",
    everyday: "공장의 생산 지시서(Build)와 생산 일정표(Schedule)와 같습니다. 지시서대로 재료를 가공해 제품을 만들고 일정표에 따라 정해진 때마다 다시 생산합니다.",
    points: [
      "Build는 job으로 구성됩니다. job 하나는 같은 로직으로 하나 이상의 출력 Dataset을 계산하며 출력이 여럿이면 항상 함께 갱신됩니다.",
      "job의 로직에는 transform뿐 아니라 Data Connection sync, health check, export 등이 있습니다.",
      "JobSpec은 job을 만드는 방법의 정의로 데이터 변환 로직이 바뀌면(예: Code Repositories에 transform 코드 커밋) 게시됩니다.",
      "Build 한 번은 출력을 한 번 계산할 뿐이므로 데이터가 계속 흐르게 하려면 Schedule로 반복 실행합니다.",
      "Schedule의 trigger가 충족되면 Build가 실행되고 이전 실행이 끝나지 않았으면 끝난 뒤에 실행됩니다.",
      "Health check는 Dataset의 상태·시간·크기·내용·스키마 문제 등을 감시하고 문제가 생기면 플랫폼 알림과 이메일로 알려 줍니다. 검사는 Dataset·Schedule·table에 만들 수 있고 Dataset용 검사는 코드로도 만들 수 있습니다.",
    ],
    doc: [
      { label: "Builds", href: D + "data-integration/builds" },
      { label: "Schedules", href: D + "data-integration/schedules" },
    ],
    related: [{ label: "Health checks", href: D + "health-checks/overview" }],
  },
  {
    id: "dataset", short: "Dataset", layer: "data", title: "Dataset",
    lead: "Dataset은 파일 묶음(보통 Parquet)과 스키마로 구성되며 변경은 트랜잭션 단위로 기록됩니다. 스키마 없는 Dataset에 비정형 파일을 담을 수도 있고 미디어 파일은 미디어 작업에 맞춘 Media set에 저장할 수도 있습니다.",
    analogy: "겉모습은 테이블이지만 내부 동작은 Git 저장소에 가깝습니다. 트랜잭션 하나가 커밋 하나에 해당합니다.",
    everyday: "수정할 때마다 저장 버전이 남는 엑셀 파일과 같습니다. 구글 문서의 버전 기록처럼 예전 시점의 내용으로 되돌릴 수 있습니다.",
    points: [
      "SNAPSHOT: 전체를 교체합니다(TRUNCATE + INSERT).",
      "APPEND: 새 파일만 추가합니다. 증분 파이프라인의 기반입니다.",
      "UPDATE: 파일을 추가하거나 덮어씁니다. 덮어쓰면 하류의 증분 처리가 깨집니다.",
      "DELETE: 현재 view에서 파일 참조만 뺍니다. 실제 파일은 지우지 않으며 주로 보존(retention) 작업에 씁니다.",
      "Iceberg table은 Dataset 대신 표 데이터를 담는 다른 리소스 유형으로 Foundry가 관리하는 Iceberg 카탈로그나 외부 카탈로그(Virtual table)로 씁니다.",
      "View는 파일 없이 backing Dataset 여러 개를 읽을 때 합쳐 보여 주며 primary key로 중복을 없앨 수 있습니다. transform의 입력으로는 쓸 수 있지만 출력으로는 쓸 수 없습니다.",
    ],
    warn: "Data Lineage → History → Rollback to transaction으로 롤백할 수 있지만 되돌아가는 것은 데이터뿐이며 로직은 그대로입니다. 보존 정책(retention)으로 삭제된 트랜잭션으로는 롤백할 수 없습니다. Object Storage v2의 Object type을 받치는 Dataset을 롤백하면 Object type이 저절로 다시 인덱싱되지 않으므로 대체 파이프라인을 실행해 다시 인덱싱해야 합니다. 보존 정책은 삭제 표시 후 보통 7일 뒤 실제로 지우며 그 이후에는 복구할 수 없습니다. 실제로 지우기 전에는 삭제 표시를 되돌릴 수 있습니다. 잘못 표시한 정책을 먼저 고치고 7일 안에 Palantir 담당자에게 연락합니다.",
    doc: D + "data-integration/datasets",
    related: [
      { label: "롤백", href: D + "data-lineage/dataset-rollback" },
      { label: "보존 정책 실행", href: D + "retention/policy-execution" },
      { label: "Iceberg tables", href: D + "data-integration/iceberg-tables" },
      { label: "Views", href: D + "data-integration/views" },
    ],
  },
  {
    id: "stream", short: "Stream", layer: "data", title: "Stream",
    lead: "Stream은 Dataset처럼 Foundry에 들어온 데이터를 담으면서 지연이 짧은(low-latency) 조회를 함께 제공합니다. Ontology의 입력 datasource로 쓰면 배치 Dataset 인프라를 벗어나 초~분 단위로 인덱싱되므로 지연에 민감한 운영 업무에 맞습니다.",
    analogy: "Kafka의 changelog 토픽에 가깝습니다. 배치로 다시 계산하는 Dataset과 달리 레코드가 들어온 순서대로 흐르고 Object에는 같은 키의 가장 최근 레코드가 반영됩니다.",
    everyday: "하루치를 모아 정리하는 장부(Dataset)와 달리 소식이 들어오는 즉시 한 줄씩 띄우는 실시간 전광판과 같습니다. 같은 항목의 새 소식이 오면 전광판에는 가장 최근 소식이 표시됩니다.",
    points: [
      "레코드는 Data Connection의 streaming sync로 가져오거나 REST API로 직접 보냅니다(push). API(publishRecords)는 레코드를 Stream 스키마로 검증하고 하나라도 맞지 않으면 묶음 전체를 거부합니다. OAuth 앱으로 보내려면 api:streams-write scope를 요청해야 합니다.",
      "Stream 기반 Object type은 Pipeline Builder나 Ontology Manager에서 설정합니다. Funnel은 레코드가 쓰인 순서대로 인덱싱하므로 상류 Pipeline Builder 파이프라인에서 primary key로 나누고(partition) 이벤트 시각 순으로 정렬해 두어야 합니다.",
      "같은 primary key는 가장 최근 업데이트가 이깁니다(most recent update wins). 레코드는 1MB를 넘을 수 없고 Object type의 property는 250개를 넘을 수 없습니다.",
      "Stream의 Viewer 권한이 있으면 그 Stream으로 만든 Object를 모두 볼 수 있습니다. 행·열 단위로 나누려면 Object security policy를 적용합니다. Restricted view는 Stream에 만들 수 없습니다.",
      "관계형 DB의 변경 데이터 캡처(CDC) 피드도 받을 수 있습니다. 스키마에 changelog 메타데이터를 설정하면 Data Connection·Stream·Pipeline Builder·Ontology가 이를 변경 이력으로 처리합니다.",
    ],
    warn: "Stream 기반 Object type은 사용자 편집과 multi-datasource object type(MDO)을 지원하지 않습니다. 편집이 필요하면 direct datasource를 쓸 수 있지만 베타 단계라 환경(enrollment)에 따라 제공되지 않을 수 있고 지금은 Pipeline Builder만 쓰기 앱으로 지원합니다.",
    doc: D + "data-integration/streams",
    related: [
      { label: "Streaming Funnel", href: D + "object-indexing/funnel-streaming-pipelines" },
      { label: "Direct datasource", href: D + "object-indexing/direct-datasources" },
      { label: "Push 수집", href: D + "data-connection/push-based-ingestion" },
      { label: "레코드 보내기 API", href: D + "api/streams-v2-resources/streams/publish-records-to-stream" },
      { label: "권한", href: D + "object-permissioning/managing-object-security" },
      { label: "CDC", href: D + "data-integration/change-data-capture" },
    ],
  },
  {
    id: "media", short: "Media set", layer: "data", title: "Media set",
    lead: "Media set은 파일 전용 저장소이고 media reference는 그 파일을 가리키는 포인터입니다.",
    analogy: "버전 관리를 켠 S3 버킷과 DB 컬럼에 저장한 S3 key의 관계와 같습니다.",
    everyday: "사진·문서를 보관하는 창고와 장부에 적어 둔 '창고 몇 번 선반' 메모의 관계와 같습니다. 같은 선반에 새 파일을 넣어도 옛 파일은 치워지지 않고 옛 메모는 계속 옛 파일을 가리킵니다.",
    points: [
      "같은 경로에 다시 업로드하면 경고 없이 새 media item으로 덮어씁니다. 기존 reference는 계속 이전 파일을 가리킵니다.",
      "덮어써진 item은 기본적으로 삭제되지 않고 버전 이력에 남으며 Build에서도 처리될 수 있습니다. 정리하려면 '덮어쓰거나 삭제된 뒤 N일 후 영구 삭제' 보존 정책을 설정합니다.",
      "Object type의 Capabilities 탭에서 media source를 지정해야 연결됩니다.",
      "reference는 Action의 파일 업로드나 Python transform으로 만들 수 있습니다.",
      "미디어는 Data Connection의 media sync로 가져오고 Code Repositories나 Pipeline Builder로 변환할 수 있습니다.",
    ],
    warn: "Media set 권한은 Object security policy와 별개입니다. 파일을 보호하려면 Media set을 따로 잠가야 합니다. 보존 기간을 줄이면 기간이 지난 item은 즉시 접근할 수 없게 되고 다시 늘려도 복구되지 않습니다.",
    doc: D + "media-sets-advanced-formats/media-overview",
    related: [
      { label: "Ontology에서 쓰기", href: D + "media-sets-advanced-formats/media-in-ontology" },
      { label: "media sync", href: D + "data-connection/core-concepts" },
      { label: "Capabilities 탭", href: D + "object-link-types/base-types" },
      { label: "덮어쓰기와 버전 이력", href: D + "media-sets-advanced-formats/importing-media" },
      { label: "보존 정책", href: D + "media-sets-advanced-formats/media-set-settings" },
      { label: "권한 분리", href: D + "object-permissioning/managing-object-security" },
    ],
  },
  {
    id: "vt", short: "Virtual table", layer: "data", title: "Virtual table",
    lead: "Virtual table은 외부 데이터 플랫폼의 테이블을 Foundry Dataset에 먼저 저장하지 않고 바로 조회하게 해 주는 포인터입니다. 다른 리소스처럼 Foundry의 권한 모델이 적용됩니다.",
    analogy: "Postgres의 foreign table처럼 데이터는 원래 시스템에 두고 Foundry에는 연결 정보와 테이블 위치만 둡니다. Foundry Dataset과 섞어 한 파이프라인에서 쓸 수 있습니다.",
    everyday: "다른 도서관의 책을 우리 도서관 목록에 올려 두고 필요할 때 그 도서관에서 바로 열람하는 상호대차와 같습니다. 책을 복사해 오지 않습니다.",
    points: [
      "Data Connection의 source(연결 정보)와 원본 시스템에서 테이블을 가리키는 locator(데이터베이스·스키마·테이블 이름)로 정의합니다.",
      "Amazon S3, ADLS·OneLake, BigQuery, Databricks, Google Cloud Storage, Snowflake를 지원하고 Foundry(베타, managed Iceberg만)도 지원하며 일부 source는 테이블을 주기적으로 자동 등록(auto-registration)할 수 있습니다.",
      "Pipeline Builder·Code Repositories의 입력과 출력, Contour 분석에 쓸 수 있습니다. Object type을 만들 때는 Ontology Manager에서 datasource로 쓰거나 Pipeline Builder에서 입력으로 씁니다.",
      "일부 source에서는 원본 시스템의 계산 엔진으로 처리하는 compute pushdown을 쓸 수 있습니다.",
    ],
    warn: "source와 테이블 유형마다 지원 기능(쓰기, 엔진 등)이 다르므로 source별 문서를 확인해야 합니다. source에서 테이블이 지워져도 자동 등록된 Virtual table은 지워지지 않고 데이터만 읽히지 않습니다.",
    doc: D + "data-integration/virtual-tables",
    related: [{ label: "Iceberg tables", href: D + "data-integration/iceberg-tables" }],
  },
  {
    id: "model", short: "Models · Modeling Objectives", mapLines: ["Models", "Modeling Objectives"], layer: "data", title: "Models · Modeling Objectives",
    lead: "Models는 Foundry 안에서 학습했거나 밖에서 가져온 머신러닝 모델을 같은 방식으로 다루는 리소스입니다. Modeling Objective는 하나의 운영 문제를 중심으로 데이터·메타데이터·모델을 모아 두는 단위이며 Modeling Objectives 앱에서 모델을 제출·평가·릴리스·배포합니다.",
    analogy: "Models는 모델 레지스트리에 올린 모델 버전에 해당합니다. Modeling Objective에 모델을 제출하는 것은 PR을 올리는 것과 같고 release와 deployment는 Staging·Production 태그로 배포하는 모델용 CI/CD입니다.",
    everyday: "Models는 회사가 쓰는 예측 도구 하나하나입니다. Modeling Objective는 '어떤 문제를 풀 도구인가'를 정해 두고 후보 도구를 비교 심사한 뒤 합격한 것을 현장에 배치하는 심사 위원회와 같습니다.",
    points: [
      "Foundry에서 학습한 모델, 밖에서 학습해 파일로 올린 모델, 밖에서 만든 컨테이너, 밖에서 호스팅하는 모델을 모두 연결할 수 있습니다.",
      "모델은 파일·가중치 같은 model artifact와 그것을 불러와 추론하는 방법을 정한 model adapter로 구성됩니다.",
      "Modeling Objective에 모델을 제출하면 변경할 수 없는 사본(submission)이 만들어지고 Objective에 정한 metric으로 다른 모델과 비교됩니다. 채택한 모델은 Staging·Production 같은 환경 태그가 붙은 release가 됩니다.",
      "batch deployment는 입력 Dataset으로 추론해 출력 Dataset에 쓰며 보통 Build Schedule로 관리합니다. live deployment는 바로 호출할 수 있는 REST API endpoint를 제공합니다. Modeling Objective를 거치지 않고 모델에서 바로 live endpoint인 direct deployment를 만들 수도 있습니다.",
      "live deployment는 model function으로 감싸 TypeScript·Python Function에서 query function처럼 호출할 수 있습니다. 2026년 2월부터 새로 만드는 model function은 Ontology에 묶입니다.",
    ],
    warn: "deployment는 환경 태그가 붙은 최신 release를 가져가도록 설정할 수 있습니다. 이렇게 설정한 Production deployment에 새 모델을 반영하려면 그 모델의 release에 Production 태그를 붙입니다.",
    doc: [
      { label: "Models", href: D + "integrate-models/integrate-overview" },
      { label: "Modeling Objectives", href: D + "model-integration/objectives" },
    ],
    related: [
      { label: "Functions on models", href: D + "functions/functions-on-models" },
      { label: "Direct deployment", href: D + "manage-models/create-a-model-deployment" },
    ],
  },
  {
    id: "funnel", short: "Funnel", layer: "onto", title: "Funnel · Materialization",
    lead: "Funnel은 Dataset·Restricted view·Stream 같은 datasource를 객체 저장소(OSv2)로 인덱싱합니다. Action으로 만든 편집은 인덱스에 즉시 반영됩니다.",
    analogy: "MySQL 원본을 검색용 Elasticsearch 인덱스로 동기화하고 앱은 인덱스만 조회하는 구조와 비슷합니다. Materialization은 원본과 편집을 합쳐 다시 테이블로 저장하는 materialized view에 해당합니다.",
    everyday: "도서관 책으로 검색용 목록(색인)을 만들어 두고 사람들은 그 목록으로 책을 찾는 것과 같습니다. Materialization은 목록에 반영된 수정 사항까지 합쳐 책을 새로 인쇄해 두는 것에 해당합니다.",
    points: [
      "Funnel 파이프라인에는 batch와 streaming 두 종류가 있습니다. 쓰기·편집의 지연을 줄여야 하면 direct datasource를 쓸 수 있습니다.",
      "Action 편집은 원본 backing Dataset이 아니라 Funnel이 내부에서 관리하는 Dataset에 저장됩니다. 이 Dataset은 원본에 새 트랜잭션이 생길 때 또는 편집이 있었다면 6시간마다 Build됩니다.",
      "Materialization은 사용자가 따로 만드는 출력 Dataset으로 원본과 편집을 합친 각 Object의 최신 상태를 담습니다. OSv2에서는 선택 사항이며 하류 파이프라인이나 대량 다운로드에 씁니다.",
    ],
    doc: [
      { label: "Funnel", href: D + "object-indexing/overview" },
      { label: "Materialization", href: D + "object-edits/materializations" },
    ],
    related: [
      { label: "편집이 적용되는 방식", href: D + "object-edits/how-edits-applied" },
      { label: "Restricted view", href: D + "security/restricted-views" },
      { label: "Stream datasource", href: D + "object-permissioning/managing-object-security" },
    ],
  },
  {
    id: "onto", short: "Ontology", layer: "onto", title: "Ontology",
    lead: "Dataset 위에 업무 의미를 부여하는 계층입니다. 업무용 앱(Workshop·OSDK)은 주로 Ontology를 읽고 씁니다. Platform SDK로 Dataset API를 호출할 수도 있습니다.",
    analogy: "ORM 모델 계층에 해당합니다. Object type = 테이블, Object = 행, Property = 컬럼, Link type = 조인/FK, Object set = WHERE 결과입니다.",
    everyday: "엑셀 표를 '고객', '주문'처럼 실제 업무에서 쓰는 말로 정리한 명부와 같습니다. 한 줄은 고객 한 명, 칸은 이름·연락처 같은 항목이고 Link는 '이 고객의 주문 목록' 같은 연결입니다.",
    points: [
      "Object의 값은 backing datasource(원본 Dataset)의 데이터와 Action 편집을 합친 것입니다. Action으로만 채우는 Object type처럼 datasource가 없는 경우도 있습니다.",
      "Link type은 1:1, 1:N, N:1, N:M 관계를 표현합니다. N:M 관계는 조인 테이블 Dataset으로 연결합니다.",
      "Object set의 예: 상태가 '지연'인 항공편 전체",
      "Shared property는 여러 Object type이 함께 쓰는 property입니다. 메타데이터는 한곳에서 관리하지만 값은 Object마다 따로 가집니다.",
      "Time series property는 Object property의 한 종류로 값 하나 대신 타임스탬프가 붙은 값의 이력을 저장합니다. Workshop에서는 Chart XY·Map·Metric Card·Object Table 위젯에서 쓸 수 있습니다. time series 서비스가 설치되어 있어야 하므로 환경에 따라 쓸 수 없을 수 있습니다.",
    ],
    doc: D + "ontology/core-concepts",
    related: [
      { label: "Link type 만들기", href: D + "object-link-types/create-link-type" },
      { label: "Materializations", href: D + "object-edits/materializations" },
      { label: "Object type 만들기", href: D + "object-link-types/create-object-type" },
      { label: "Platform SDK와 OSDK", href: D + "api/v2/general/overview/sdks" },
      { label: "Shared property", href: D + "object-link-types/shared-property-overview" },
      { label: "Time series property", href: D + "workshop/time-series-properties" },
    ],
  },
  {
    id: "interfaces", short: "Interfaces", layer: "onto", title: "Interfaces",
    lead: "여러 Object type이 공유하는 공통 형태를 정의합니다. Interface를 쓰는 워크플로는 이를 구현한 Object type들을 한꺼번에 다룰 수 있습니다.",
    analogy: "TypeScript의 interface와 같습니다. Facility interface를 Airport와 Manufacturing Plant가 구현하면 Facility를 받는 코드는 두 타입을 모두 처리합니다.",
    everyday: "'시설'이라는 공통 양식과 같습니다. 공항·공장·정비고는 각자 칸이 다르지만 '시설 이름·위치'라는 공통 칸이 있어서 시설 목록 하나로 함께 관리할 수 있습니다.",
    points: [
      "Interface는 interface property, link type 제약, action type 제약(베타), 메타데이터로 구성됩니다.",
      "하나의 interface를 여러 Object type이 구현할 수 있습니다. 새 Object type이 구현하면 기존 워크플로가 수정 없이 바로 호환됩니다.",
      "interface를 확장(extend)해 속성을 물려받는 하위 interface를 만들 수 있습니다.",
    ],
    warn: "플랫폼 기능마다 interface 지원 수준이 다르므로 쓰기 전에 지원 범위를 확인해야 합니다.",
    doc: D + "interfaces/interface-overview",
    related: [],
  },
  {
    id: "action", short: "Action type", layer: "logic", title: "Action type",
    lead: "Object를 수정하는 방법을 정의합니다. Action 한 번 실행이 트랜잭션 하나입니다.",
    analogy: "서버 측 쓰기 API(POST)와 서버 측 validation을 합친 것입니다.",
    everyday: "정해진 양식의 신청서와 같습니다. 양식대로 작성하고 결재 조건을 통과해야만 내용이 실제로 반영됩니다.",
    points: [
      "Parameters: 요청 body에 해당합니다.",
      "Rules: 무엇을 바꿀지 정합니다(생성·수정·삭제·링크).",
      "Submission criteria: 제출 가능 여부를 정합니다. 사용자 그룹·파라미터·Object 상태를 조합해 조건을 만듭니다.",
      "제출하려면 편집 대상 Object type·Link type과 그 datasource를 볼 수 있어야 하고 편집 권한도 있어야 합니다. Action으로만 편집하는 타입은 대상 Object의 Read 권한, 그 밖의 타입은 writeback Dataset의 Edit 권한, Restricted view 기반 타입은 edit policy 통과가 필요합니다.",
      "action log를 쓰는 Action은 action log Object type에 대한 권한도 있어야 제출할 수 있습니다.",
    ],
    warn: "Submission criteria만 통과한다고 제출할 수 있는 것은 아닙니다. Object security policy 같은 행·열 통제는 Action이 읽는 데이터를 거릅니다. 이 통제는 Action이 쓴 결과로 전파되지 않고 쓰기 대상에는 그 대상의 통제가 적용됩니다.",
    doc: D + "action-types/overview",
    related: [
      { label: "Submission criteria", href: D + "action-types/submission-criteria" },
      { label: "Action 권한", href: D + "action-types/permissions" },
      { label: "권한 전파", href: D + "security/access-control-propagation" },
    ],
  },
  {
    id: "function", short: "Function", layer: "logic", title: "Function",
    lead: "요청 시점에 실행되는 서버 코드입니다. Ontology 조회, 링크 탐색, 편집 계산을 담당합니다.",
    analogy: "AWS Lambda나 Next.js API route에 가깝습니다. Transform이 배치라면 Function은 요청 즉시 실행됩니다.",
    everyday: "물어볼 때마다 바로 답을 계산해 주는 계산기와 같습니다. 밤새 미리 만들어 두는 transform과 달리 요청이 들어온 순간 계산합니다.",
    points: [
      "Query: 부수 효과가 없는 읽기 전용 함수입니다. API gateway로 노출하는 것은 선택 사항이며 편집이 필요하면 Action을 씁니다.",
      "Edit function: 편집 내용을 계산만 합니다. Function-backed action으로 실행해야 저장됩니다.",
      "TypeScript v2나 Python이 권장됩니다.",
      "관리자가 extended function execution을 허용하면 function 안에서 Action을 호출할 수 있습니다. 이때도 저장은 Action을 거칩니다.",
    ],
    warn: "Edit function을 helper에서 실행해도 결과는 저장되지 않습니다. Function으로 Object를 수정하는 방법은 그 Function을 쓰는 Action을 실행하는 것뿐입니다.",
    doc: D + "functions/overview",
    related: [
      { label: "Ontology edits", href: D + "functions/edits-overview" },
      { label: "Query 함수", href: D + "functions/query-functions" },
      { label: "언어별 지원", href: D + "functions/language-feature-support" },
      { label: "Function 권한", href: D + "functions/permissions" },
      { label: "Function-backed action", href: D + "functions/use-functions" },
    ],
  },
  {
    id: "cm", short: "Compute module", layer: "logic", title: "Compute module",
    lead: "어떤 언어로 작성한 코드든 Docker 컨테이너로 Foundry 안에서 실행합니다. 부하에 따라 컨테이너 수가 자동으로 늘거나 줄어듭니다.",
    analogy: "Google Cloud Run 같은 서버리스 컨테이너 서비스에 가깝습니다. Docker 이미지를 올리면 플랫폼이 실행과 확장을 맡습니다.",
    everyday: "회사 밖 전문 업체에 일을 맡기는 것과 같습니다. 업체는 자기에게 익숙한 방식(언어·도구)으로 일하고 Application permissions를 쓰면 누가 맡겼든 업체 자신의 출입 권한으로 일합니다.",
    points: [
      "Function mode: 컨테이너에 함수를 올려 Workshop·Slate, Developer Console의 OSDK 앱, TypeScript function에서 호출합니다. TypeScript function에서 부를 때는 5분이 넘으면 시간 초과입니다.",
      "Pipeline mode: 외부 소스의 데이터를 Stream·Dataset·Media set으로 가져오는 것처럼 입력을 받아 출력으로 처리합니다. job token은 입출력 리소스에만 쓸 수 있습니다.",
      "Function mode 권한은 '플랫폼 권한 없음'과 'Application permissions' 중에서 고릅니다. Application permissions는 호출한 사용자와 관계없이 연결된 서비스 유저의 권한으로 동작합니다.",
    ],
    warn: "Application permissions는 일부 환경(enrollment)에서는 제공되지 않을 수 있습니다.",
    doc: D + "compute-modules/overview",
    related: [
      { label: "실행 모드", href: D + "compute-modules/execution-modes" },
      { label: "함수 호출", href: D + "compute-modules/functions" },
    ],
  },
  {
    id: "automate", short: "Automate", layer: "logic", title: "Automate",
    lead: "조건과 효과(effect)를 정의해 두면 조건이 충족될 때 효과를 자동으로 실행하는 비즈니스 자동화 앱입니다.",
    analogy: "GitHub Actions의 schedule·이벤트 트리거와 비슷합니다. 다만 트리거가 코드 이벤트가 아니라 시간이나 Ontology 데이터의 변화입니다.",
    everyday: "'매주 월요일 9시에 보고서 보내기', '긴급 알림이 새로 생기면 담당자에게 알리기' 같은 업무 규칙을 정해 두면 알아서 처리해 주는 자동 비서입니다.",
    points: [
      "조건: 시간 기반(예: 매주 월요일 오전 9시), Ontology 데이터 기반(예: 우선순위가 높은 Alert Object 추가) 또는 둘의 조합",
      "효과: Action 제출, AIP Logic 함수 실행, Function 실행, 플랫폼·이메일 알림",
      "조건은 계속 감시하거나 일정에 맞춰 확인합니다.",
    ],
    doc: D + "automate/overview",
    related: [],
  },
  {
    id: "aip", short: "AIP Logic", layer: "logic", title: "AIP Logic · AIP Chatbot Studio",
    lead: "AIP Logic은 LLM과 Ontology를 활용하는 AI 함수를 만드는 도구이고 AIP Chatbot Studio는 LLM·Ontology·문서·도구로 동작하는 챗봇을 만드는 도구입니다.",
    analogy: "AIP Logic은 LLM 호출을 조합해 만드는 서버 함수와 같습니다. Object나 텍스트를 입력받아 결과를 돌려주거나 Ontology 편집을 만듭니다. Chatbot Studio는 앱에 붙이는 LLM 챗봇 빌더입니다.",
    everyday: "AIP Logic은 서류를 읽고 판단해 처리안을 내는 AI 실무자, Chatbot Studio는 회사 자료를 알고 질문에 답하거나 업무를 대신 처리하는 AI 상담 창구와 같습니다.",
    points: [
      "Logic 함수는 Object나 문자열을 입력받아 Object·문자열을 돌려주거나 Ontology 편집을 만듭니다.",
      "편집을 Ontology에 저장하려면 Logic 함수를 게시하고 Action에서 호출해야 합니다.",
      "Execute function 블록으로 TypeScript·Python function이나 다른 Logic 함수를 호출할 수 있습니다.",
      "Logic 함수를 자동화해 편집을 바로 적용하거나 사람이 검토하도록 대기시킬(staged) 수 있습니다.",
      "AIP Chatbot Studio의 예전 이름은 AIP Agent Studio입니다. 챗봇은 앱에 통합해 읽기·쓰기 워크플로를 처리합니다.",
      "AIP Evals는 AIP Logic 함수·챗봇 함수·코드 함수를 test case와 evaluation function으로 평가하는 테스트 환경입니다. LLM 결과가 실행마다 달라지는 점을 감안해 이전 버전이나 다른 모델과 결과를 비교하고 실행 간 편차를 확인합니다.",
    ],
    warn: "플랫폼 보안은 LLM이 작업에 필요한 데이터에만 접근하도록 제한하지만 모델의 출력이나 모델이 만든 Ontology 편집까지 통제하지는 않습니다.",
    doc: [
      { label: "AIP Logic", href: D + "logic/overview" },
      { label: "AIP Chatbot Studio", href: D + "chatbot-studio/overview" },
    ],
    related: [
      { label: "Logic 핵심 개념", href: D + "logic/core-concepts" },
      { label: "Logic 블록", href: D + "logic/blocks" },
      { label: "AIP Evals", href: D + "aip-evals/overview" },
    ],
  },
  {
    id: "workshop", short: "Workshop", layer: "app", title: "Workshop",
    lead: "Ontology 위에서 앱을 조립하는 노코드 빌더입니다. 웹과 모바일 앱을 만들 수 있습니다.",
    analogy: "Retool과 비슷합니다. Layout = JSX 구조, Widget = 컴포넌트, Variable = useState, Event = 이벤트 핸들러입니다.",
    everyday: "파워포인트에서 도형을 끌어다 놓듯 표·차트·버튼을 배치해 업무 화면을 만드는 도구입니다. 버튼을 누르면 신청서(Action)가 제출되는 식으로 연결됩니다.",
    points: [
      "쓰기는 Action, 복잡한 계산은 Function에 연결합니다.",
      "기본 위젯으로 부족하면 Custom widget으로 직접 작성한 프론트엔드 코드를 넣을 수 있습니다.",
      "기본 도구를 넘어서는 완전한 맞춤 화면이 필요하면 OSDK React 앱을 만듭니다.",
      "OSDK로 만든 React 앱은 Iframe 위젯으로, Quiver 대시보드는 그대로 Workshop 안에 넣을 수 있습니다.",
      "Carbon은 Workshop 모듈·Action·Quiver 분석 같은 앱과 리소스를 묶어 사용자 그룹별 작업 공간(workspace)을 만듭니다. 작업 공간 밖으로 이동하는 것을 막을 수도 있습니다.",
      "Pilot(베타)은 자연어 설명으로 Object type·Action type 같은 Ontology 요소와 OSDK React 앱 또는 Workshop에 넣을 Custom widget을 만듭니다. 환경에 따라 제공되지 않을 수 있습니다.",
      "Slate는 드래그 앤 드롭으로 앱과 대시보드를 만드는 또 다른 도구로 CSS로 화면의 모든 스타일을 바꿀 수 있습니다. Object 데이터·Function·Action과 함께 Foundry 외부의 데이터베이스·API 데이터도 쓸 수 있습니다.",
    ],
    doc: D + "workshop/overview",
    related: [
      { label: "앱 빌딩 개요", href: D + "app-building/overview" },
      { label: "Custom widget", href: D + "custom-widgets/overview" },
      { label: "OSDK React 앱", href: D + "ontology-sdk-react-applications/overview" },
      { label: "Quiver 대시보드", href: D + "quiver/overview" },
      { label: "Slate", href: D + "slate/overview" },
      { label: "Carbon", href: D + "carbon/overview" },
      { label: "Pilot", href: D + "pilot/overview" },
    ],
  },
  {
    id: "osdk", short: "OSDK", layer: "app", title: "OSDK · Developer Console",
    lead: "OSDK는 Ontology에서 생성되는 타입 있는 클라이언트이고 Developer Console은 커스텀 앱을 관리하는 콘솔입니다.",
    analogy: "Prisma Client처럼 스키마(Ontology)에서 생성되는 타입 있는 클라이언트입니다. Developer Console은 GitHub의 OAuth App 설정처럼 앱을 등록하고 접근 범위를 관리하는 곳입니다.",
    everyday: "Foundry 데이터를 회사가 직접 만든 앱에서 쓸 수 있게 해 주는 전용 연결 도구입니다. Developer Console은 그 앱을 등록하고 어떤 데이터까지 쓸 수 있는지 정하는 관리 창구입니다.",
    points: [
      "토큰의 리소스 접근 범위 = 사용자(또는 서비스 유저) 권한 ∩ 앱의 resource restrictions",
      "앱 제한에는 접근할 리소스를 정하는 resource restrictions와 할 수 있는 작업을 정하는 operation restrictions 두 종류가 있습니다.",
      "앱이 토큰을 요청할 때 고를 수 있는 것은 api:use-ontologies-read 같은 작업(operation) scope뿐입니다. scope를 빈 값([])으로 요청하면 앱의 operation restrictions 전체가 적용됩니다. scope 없이 토큰을 요청하면 앱 제한이 허용하는 사용자 권한 전부가 적용됩니다.",
      "앱은 기본적으로 제한(restricted) 상태로 만들어집니다. 제한 없는(unrestricted) 앱은 사용자 권한만으로 접근이 결정되므로 신뢰할 수 있는 코드에만 써야 합니다. unrestricted 앱이 Authorization code 방식을 쓰면 scope를 반드시 요청해야 합니다.",
      "웹 호스팅은 정적 에셋만 지원하고 서버 코드는 실행할 수 없습니다. 커스텀 404 페이지가 없으면 SPA로 간주합니다. 파일은 최대 1,000개, 전체 20MB까지 올릴 수 있습니다.",
      "Platform SDK는 어느 환경(enrollment)에서나 Ontology를 포함한 모든 Foundry API를 호출하는 범용 라이브러리이고 OSDK는 각 환경에서 생성되어 Platform SDK 위에 Ontology를 더 다루기 쉽게 추상화한 라이브러리입니다.",
    ],
    warn: "앱 제한은 앱이 받을 수 있는 권한의 보장된 상한입니다. 요청 scope는 작업(operation) 범위만 좁힙니다. 리소스 접근은 앱의 resource restrictions와 사용자 권한만으로 정해집니다.",
    doc: [
      { label: "OSDK", href: D + "ontology-sdk/overview" },
      { label: "Developer Console", href: D + "developer-console/overview" },
    ],
    related: [
      { label: "앱 제한", href: D + "developer-console/application-restrictions" },
      { label: "웹 호스팅", href: D + "developer-console/deploy-custom-application-on-foundry" },
      { label: "Platform SDK와 OSDK", href: D + "api/v2/general/overview/sdks" },
    ],
  },
  {
    id: "analytics", short: "Contour · Quiver · Object Explorer", layer: "app", title: "Contour · Quiver · Object Explorer",
    mapLines: ["Contour · Quiver", "Object Explorer"],
    lead: "코드 없이 데이터를 분석하고 대시보드를 만드는 앱들입니다. Contour는 Dataset, Quiver는 Object와 시계열, Object Explorer는 Object 검색과 탐색에 맞춰져 있습니다.",
    analogy: "Metabase나 Tableau 같은 BI 도구에 해당합니다. Contour는 테이블(Dataset) 기반, Quiver는 ORM 모델(Object) 기반 분석이고 Object Explorer는 관리자 화면의 검색·필터 목록과 비슷합니다.",
    everyday: "엑셀의 필터·피벗·차트 기능을 떼어 낸 분석 도구들입니다. 데이터를 걸러 보고 차트로 만들고 다른 사람과 대시보드로 공유합니다.",
    points: [
      "Contour: 코드 없이 시각화·필터·변환을 하고 분석 결과를 새 Dataset으로 저장합니다. Ontology에 매핑되지 않은 데이터를 분석할 때 적합합니다.",
      "Quiver: Object와 시계열 데이터를 분석하고 연결된 Object type을 따라가며 탐색합니다. 대시보드를 Workshop 같은 앱에 넣을 수 있습니다.",
      "Quiver는 transform table과 Dataset도 다루고 Code function 카드로 Function을 불러 쓰며 Action으로 분석 결과를 Ontology에 쓸 수 있습니다.",
      "Insight: Ontology 데이터를 필터·링크 탐색·집계 단계로 이어 분석합니다. SQL 쿼리를 쓸 수 있고 Action으로 분석 결과에서 Object를 만들고 고치거나 지울 수 있습니다.",
      "Notepad는 다른 앱의 차트·표·Object를 넣는 문서 편집기로 템플릿으로 정기 보고서를 만듭니다. Fusion은 Dataset을 조회하고 결과를 Dataset으로 다시 쓰는 스프레드시트입니다.",
      "Object Explorer: 키워드나 속성 필터로 Object를 찾고 찾은 Object set에 Action을 일괄 실행하거나 Quiver로 넘길 수 있습니다. 비기술 사용자를 위한 도구입니다.",
    ],
    doc: [
      { label: "Contour", href: D + "contour/overview" },
      { label: "Quiver", href: D + "quiver/overview" },
      { label: "Object Explorer", href: D + "object-explorer/overview" },
    ],
    related: [
      { label: "분석 도구 비교", href: D + "analytics/types-of-analysis" },
      { label: "Code function 카드", href: D + "quiver/card-code-function-object-set" },
      { label: "Insight", href: D + "insight/overview" },
      { label: "Notepad", href: D + "notepad/overview" },
      { label: "Fusion", href: D + "fusion/overview" },
    ],
  },
  {
    id: "objectviews", short: "Object Views", layer: "app", title: "Object Views",
    lead: "Object Views는 Object 하나에 관한 정보를 모아 보여 주는 재사용 화면입니다. property 값, 연결된 Object, 관련 앱을 한곳에 보여 줍니다.",
    analogy: "관리자 화면의 상세 페이지(detail view)와 같습니다. 모든 타입에 기본 상세 페이지가 자동으로 생기고 필요하면 직접 만든 페이지로 바꿀 수 있습니다.",
    everyday: "고객 한 명의 카드를 펼치면 기본 정보와 주문 이력과 관련 서류가 한 화면에 모여 있는 고객 카드철과 같습니다.",
    points: [
      "Standard Object View는 Object type 설정에 따라 자동으로 만들어지며 모든 Object type에 있습니다.",
      "Configured Object View는 Workshop으로 만드는 맞춤 화면입니다. 만들면 기본 화면이 되지만 사용자는 언제든 standard 화면으로 바꿔 볼 수 있습니다.",
      "Full Object View는 모든 관련 정보를 보여 주는 전체 화면이고 Panel Object View는 다른 앱 안에 넣어 그 업무에 필요한 핵심 정보만 보여 주는 화면입니다.",
    ],
    doc: D + "object-views/overview",
    related: [],
  },
  {
    id: "omcp", short: "Ontology MCP", layer: "app", title: "Ontology MCP",
    lead: "Ontology MCP는 Developer Console 앱의 Ontology 리소스를 MCP(Model Context Protocol) 도구로 공개하는 기능입니다. 외부 AI 에이전트가 MCP client로 연결해 Object를 읽고 Action을 실행합니다.",
    analogy: "OSDK가 사람이 작성한 코드를 위한 클라이언트라면 Ontology MCP는 LLM 에이전트를 위한 API 서버입니다. 앱에 넣은 Object type은 SQL 도구 하나로 읽고 Action type과 query function은 각각 하나의 도구가 됩니다.",
    everyday: "외부 AI 비서에게 회사 업무 창구의 정해진 양식만 쓰도록 허락하는 것과 같습니다. 비서는 허락된 명부를 조회하고 허락된 신청서만 낼 수 있습니다.",
    points: [
      "앱에 포함한 Object type은 SQL 도구로 읽고 Action type과 query function은 각각 별도 도구로 호출합니다. AIP Logic이나 AIP 챗봇으로 만든 로직도 함수로 저장해 도구로 공개할 수 있습니다.",
      "에이전트가 실행할 수 있는 Action은 Developer Console 앱의 application restrictions로 제한합니다.",
      "Microsoft Copilot Studio·Google Gemini Enterprise 같은 외부 AI 앱은 별도 코드 없이 연결하고 LangChain 같은 프레임워크로 만든 에이전트도 연결할 수 있습니다.",
      "Palantir MCP는 목적이 다릅니다. Ontology를 만드는 개발자용으로 AI IDE·에이전트가 Object type·Link type·Action type 같은 구조를 만들고 고치게 하지만 Ontology 데이터를 쓰지는 못합니다.",
    ],
    warn: "로컬 기기에서 Palantir AIP 밖에서 호스팅되는 LLM과 함께 Ontology MCP를 켜면 환경의 데이터를 외부 MCP client가 사용할 수 있게 됩니다. 켜기 전에 조직의 데이터 거버넌스 정책을 확인하고 앱 제한과 권한으로 민감한 리소스를 막아야 합니다.",
    doc: D + "ontology-mcp/overview",
    related: [
      { label: "샘플 아키텍처", href: D + "ontology-mcp/sample-architecture" },
      { label: "Palantir MCP", href: D + "palantir-mcp/overview" },
      { label: "앱 제한", href: D + "developer-console/application-restrictions" },
    ],
  },
  {
    id: "project", short: "Project · Role · Marking", layer: "sec", title: "Project · Role · Marking",
    lead: "Project는 리소스를 묶는 작업 단위이자 역할 부여(discretionary) 권한의 경계입니다. 리소스에 접근하려면 Role이 있어야 하고 필수 통제(Organization, Marking, CBAC)를 모두 통과해야 합니다.",
    analogy: "Role은 MySQL의 GRANT처럼 무엇을 할 수 있는지 정합니다. Marking은 모든 요청 앞에 붙는 필수 검사 미들웨어와 같아서 하나라도 통과하지 못하면 GRANT와 관계없이 차단됩니다.",
    everyday: "Role은 사무실 출입증의 등급(보기만 가능, 편집 가능 등)과 같습니다. Marking은 '기밀' 표시가 붙은 서류실의 추가 잠금이라 출입증 등급이 높아도 기밀 허가가 없으면 들어갈 수 없습니다.",
    points: [
      "기본 Role(Owner·Editor·Viewer·Discoverer)은 프로젝트 단위의 GRANT로 무엇을 할 수 있는지를 정합니다.",
      "Marking은 all-or-nothing입니다. 하나라도 통과하지 못하면 Role과 관계없이 접근할 수 없습니다.",
      "Marking은 명시적으로 제거하지 않는 한 파생 데이터에도 전파됩니다. 접근을 막는 장치이며 권한을 부여하지는 않습니다.",
      "Marking 외에 Organization과 Classification-based Access Controls(CBAC)도 필수 통제로 함께 적용됩니다.",
      "Object type 같은 Ontology 리소스도 Project에 저장해 Project Role로 권한을 관리합니다. 이 방식은 이전 모델인 ontology roles와 datasource-derived 권한을 대체하며 새 Ontology에는 기본으로 켜져 있고 기존 Ontology는 owner가 켠 뒤 리소스를 migration해야 합니다. Default Ontology에는 아직 제공되지 않습니다.",
      "Compass는 Foundry의 파일 시스템으로 Project·폴더·리소스를 정리하고 관리하며 Quicksearch는 앱·Object·Dataset 같은 리소스를 찾는 검색 도구입니다. Quicksearch는 기존 권한을 그대로 따르므로 접근 권한이 없는 콘텐츠는 결과에 보이지 않고 Discover 권한이 있는 콘텐츠는 Request access 안내로 열립니다.",
    ],
    warn: "Editor Role이 있어도 PII Marking의 멤버가 아니면 해당 데이터에 접근할 수 없습니다.",
    doc: [
      { label: "Project · Role", href: D + "security/projects-and-roles" },
      { label: "Marking", href: D + "security/markings" },
    ],
    related: [
      { label: "Ontology 권한", href: D + "object-permissioning/ontology-permissions" },
      { label: "Compass", href: D + "compass/overview" },
      { label: "Quicksearch", href: D + "getting-started/quicksearch" },
    ],
  },
  {
    id: "osp", short: "Object security policy", layer: "sec", title: "Object security policy",
    lead: "Object의 행 단위 조회 권한입니다. Property security policy와 함께 쓰면 셀 단위까지 제어할 수 있습니다.",
    analogy: "Postgres RLS에 해당합니다. 모든 SELECT에 DB가 자동으로 WHERE 조건을 붙이는 것과 같습니다.",
    everyday: "같은 명부를 열어도 사람마다 자기 담당 고객의 줄만 보이도록 나머지를 자동으로 가려 주는 것과 같습니다.",
    points: [
      "조건은 granular policy로 작성합니다. 사용자 속성(그룹 ID 등)과 property 값을 비교하며 이름이 아니라 ID를 씁니다.",
      "Dataset 권한과는 분리됩니다. 정책이 있으면 backing Dataset의 Viewer 권한 없이도 Object를 볼 수 있습니다.",
      "원본의 필수 통제(Marking·Organization·CBAC)를 기본으로 물려받으며 정책에서 필수 통제를 더하거나 필요 없는 것을 제거할 수 있습니다.",
      "변경은 거의 즉시 반영됩니다. 반면 Restricted view(Dataset용 RLS)는 정책을 바꾼 뒤 파이프라인을 다시 Build해야 반영됩니다.",
    ],
    warn: "Ontology 안에서만 적용되므로 원본 Dataset은 따로 잠가야 합니다. 이전 datasource-derived 권한 모델을 쓰는 환경에서는 Dataset 권한도 여전히 필요합니다.",
    doc: D + "object-permissioning/object-security-policies",
    related: [
      { label: "Restricted view", href: D + "security/restricted-views" },
      { label: "정책 방식 비교", href: D + "object-permissioning/managing-object-security" },
      { label: "Granular policy", href: D + "platform-security-management/manage-granular-policies" },
    ],
  },
  {
    id: "rv", short: "Restricted view", layer: "sec", title: "Restricted view",
    lead: "Restricted view는 Dataset에서 사용자가 볼 권한이 있는 행만 보이게 합니다. backing Dataset 위에 만들며 그 행으로 만든 Object에도 같은 행 단위 통제가 적용됩니다.",
    analogy: "원본 테이블로 만든 materialized view에 Postgres RLS를 건 것과 비슷합니다. 원본이 바뀌면 view가 자동으로 다시 계산(Build)되지만 정책을 바꾼 뒤에도 다시 Build해야 새 정책이 적용됩니다.",
    everyday: "원본 장부 앞에 둔 열람 창구와 같습니다. 창구는 찾아온 사람의 소속을 확인해 볼 수 있는 줄만 보여 주고 열람 규칙을 바꾸면 창구의 열람본을 다시 만들어야 새 규칙이 적용됩니다.",
    points: [
      "정책은 granular policy로 작성합니다. 사용자 속성, backing Dataset의 컬럼, 특정 값(문자열·Boolean·숫자·배열)을 비교해 조건을 만들며 사용자별로 거르려면 사용자 속성과 비교하는 항이 하나 이상 있어야 합니다.",
      "Owner Role이나 필요한 권한이 있는 사용자가 Dataset의 우클릭 메뉴로 하류에 만듭니다. 만들면 입력 Dataset이 갱신될 때마다 다시 Build하는 Schedule이 자동으로 생깁니다.",
      "Ontology Manager에서 Dataset처럼 Object type의 datasource로 고를 수 있습니다. 특정 primary key의 Object에 접근할 수 있는지는 그 행에 접근할 수 있는지로 정해집니다.",
      "Dataset에만 만들 수 있고 Stream 등 다른 datasource에는 만들 수 없습니다. transform처럼 새 Dataset을 만드는 배치 작업의 입력으로도 쓸 수 없습니다.",
    ],
    warn: "정책은 사용자가 읽는 순간에 행을 거를 뿐 읽은 뒤의 데이터로 전파되지 않습니다. Function 반환값, Action 편집, AIP Logic 도구 호출, OSDK 응답, writeback, 내보내기로 넘어간 데이터에는 원본 정책이 따라가지 않습니다. Object security policy와 Property security policy도 같습니다. 파생 데이터까지 보호하려면 backing Dataset에 Marking을 함께 겁니다. 정책을 바꾸면 파이프라인을 다시 Build해야 읽기에 반영됩니다. Object 보안에는 대부분 Object security policy가 권장되며 변경도 거의 즉시 반영됩니다. Restricted view는 backing Dataset을 Ontology 밖(예: Code Workspaces)에서도 행 단위로 보호해야 할 때 적합합니다.",
    doc: D + "security/restricted-views",
    related: [
      { label: "정책 방식 비교", href: D + "object-permissioning/managing-object-security" },
      { label: "Granular policy", href: D + "platform-security-management/manage-granular-policies" },
      { label: "권한 전파", href: D + "security/access-control-propagation" },
    ],
  },
  {
    id: "oauth", short: "OAuth", layer: "sec", title: "OAuth",
    lead: "Authorization code 방식은 사용자를 대신해 동작하고 Client credentials 방식은 서비스 유저(앱 전용 계정)로 동작합니다.",
    analogy: "'Google로 로그인'과 서버 간 API 키의 차이와 같습니다.",
    everyday: "'카카오로 로그인'처럼 각자 자기 계정으로 앱에 들어가는 방식과 회사 공용 계정 하나로 모두가 같이 쓰는 방식의 차이입니다.",
    points: [
      "브라우저 앱처럼 client secret을 안전하게 보관할 수 없는 public client는 PKCE가 필수입니다.",
      "PKCE는 로그인마다 새 verifier를 만들어 인가 코드 탈취를 막는 장치입니다. OSDK의 @osdk/oauth(createPublicOauthClient)가 verifier 생성과 S256 challenge를 자동으로 처리합니다.",
      "Client credentials 방식은 client secret이 필요하며 일반 Foundry 사용자와 연결되지 않는 서비스 유저 작업을 위한 것입니다.",
      "offline_access scope를 요청하면 refresh token을 받습니다. refresh token은 쓸 때마다 새것으로 바뀌며 30일 넘게 쓰지 않으면 무효가 됩니다.",
    ],
    warn: "client secret은 브라우저 코드에 넣으면 안 됩니다. public client는 secret을 안전하게 보관할 수 없습니다.",
    doc: D + "platform-security-third-party/writing-oauth2-clients",
    related: [
      { label: "클라이언트 등록", href: D + "platform-security-third-party/register-3pa" },
      { label: "@osdk/oauth 소스", href: "https://github.com/palantir/osdk-ts/blob/main/packages/oauth/src/createPublicOauthClient.ts" },
    ],
  },
  {
    id: "approvals", short: "Approvals · Checkpoints", mapLines: ["Approvals", "Checkpoints"], layer: "sec", title: "Approvals · Checkpoints",
    lead: "Approvals는 권한이 없는 변경을 request로 올리고 검토자가 승인하면 그 변경을 실제로 적용(invoke)하는 앱입니다. Checkpoints는 민감한 작업 전에 사용자에게 사유를 묻고 그 기록을 검토할 수 있게 남기는 데이터 거버넌스 도구입니다.",
    analogy: "Approvals는 GitHub PR의 필수 리뷰(CODEOWNERS)와 비슷합니다. request 하나에 담긴 변경(task)마다 담당 검토자가 승인해야 하고 모두 승인되면 적용(invoke)됩니다. Checkpoints는 운영 DB 접속이나 데이터 반출 전에 사유를 입력하게 하고 감사 로그에 남기는 접근 게이트웨이와 같습니다.",
    everyday: "Approvals는 회사의 전자결재와 같습니다. 결재 문서 하나에 여러 항목이 있으면 항목마다 담당 결재자가 승인해야 처리됩니다. Checkpoints는 보안 구역에 들어가거나 자료를 반출할 때 출입 대장에 목적을 적게 하는 것과 같습니다.",
    points: [
      "request는 하나 이상의 task로 구성되며 모든 task가 승인되어야 invoke되어 변경이 적용됩니다. task 예: 그룹 멤버십, Project 접근, Marking 접근, Project 참조 추가, Ontology proposal",
      "task마다 승인할 수 있는 검토자(eligible reviewer)가 다릅니다. 예를 들어 Project 접근은 그 Project의 Owner가 승인하고 Marking 접근은 그 Marking에 Manage permissions가 있는 관리자가 승인합니다.",
      "상태에는 Pending approval, Changes requested, Action required, Closed, Rejected and Closed, Completed가 있습니다. 닫힌 request는 다시 열 수 없고 완료된 request는 과거 결정의 감사 기록으로 남습니다.",
      "Checkpoints는 Action 제출, Contour·Quiver export, 그룹·Marking 멤버 변경, Project Role 부여, 로그인 등 60개가 넘는 상호작용에 붙일 수 있습니다. 사유는 시각·사용자·관련 리소스와 함께 기록되어 관리자가 검토합니다.",
      "Global Branching proposal을 만들면 Ontology proposal이 자동으로 생기고 Global Branching proposal을 병합할 때 함께 병합됩니다. 이 Ontology proposal은 Approvals에서 task의 한 종류로 다뤄집니다.",
    ],
    warn: "모든 task가 승인되어도 필수 checkpoint가 비어 있으면 Action required 상태로 남아 invoke되지 않으며 검토자가 대신 제출할 수 있습니다. Submit action checkpoint는 Workshop·Object Views·Object Explorer처럼 UI에서 사용자가 직접 제출한 Action에만 적용됩니다. Automate처럼 비동기로 제출하거나 API·OSDK로 제출한 Action에는 적용되지 않습니다.",
    doc: [
      { label: "Approvals", href: D + "approvals/overview" },
      { label: "Checkpoints", href: D + "checkpoints/overview" },
    ],
    related: [
      { label: "Checkpoint type", href: D + "checkpoints/checkpoint-types" },
      { label: "Ontology proposal 검토", href: D + "ontologies/review-ontology-proposals" },
      { label: "리소스 보호", href: D + "global-branching/resource-protection-and-approval-policies" },
    ],
  },
  {
    id: "oma", short: "Ontology Manager", layer: "ops", title: "Ontology Manager",
    lead: "Object type·Link type·Action type·Interface 같은 Ontology 리소스를 만들고 관리하는 앱입니다. Function도 여기서 살펴볼 수 있습니다.",
    analogy: "MySQL Workbench의 스키마 편집 기능과 관리 콘솔을 합친 것에 가깝습니다.",
    everyday: "명부에 어떤 칸을 둘지 정하고 신청서 양식을 설계하는 관리자 화면입니다.",
    points: [
      "Object type을 만들 때 메타데이터, backing datasource, 속성 매핑, 키(primary key·title key)를 지정합니다.",
      "Action으로만 데이터를 채울 Object type은 datasource 없이 만들 수 있습니다. 이 경우 Object type을 프로젝트에 저장하고 누가 Object를 볼 수 있는지 정하는 Object security policy를 설정해야 합니다.",
      "보호된 리소스는 브랜치에서 수정하고 proposal을 거쳐 병합해야 합니다. 보호는 리소스 owner가 켜거나 끕니다.",
    ],
    warn: "SuperRepo(Ontology-as-code)는 베타 단계이며 공식 문서에 따르면 환경(enrollment)에 따라 제공되지 않을 수 있습니다.",
    doc: D + "ontology-manager/overview",
    related: [
      { label: "Object type 만들기", href: D + "object-link-types/create-object-type" },
      { label: "리소스 보호", href: D + "global-branching/resource-protection-and-approval-policies" },
      { label: "Interface 지원 앱", href: D + "interfaces/interface-overview" },
      { label: "SuperRepo", href: D + "superrepo/overview" },
    ],
  },
  {
    id: "branch", short: "Global Branching", layer: "ops", title: "Global Branching",
    lead: "여러 앱에 걸친 변경을 브랜치 하나로 묶어 테스트한 뒤 Main에 병합합니다. 2026년 5월에 GA가 되었습니다.",
    analogy: "Git feature branch와 PR에 해당합니다. 다만 코드뿐 아니라 파이프라인·Ontology·화면까지 함께 다룹니다.",
    everyday: "원본을 바로 고치지 않고 사본에서 먼저 고쳐 본 뒤 검토를 받아 원본에 반영하는 방식입니다. 구글 문서의 '제안 모드'와 비슷합니다.",
    points: [
      "지원 대상: Code Repositories, Pipeline Builder, Ontology(Action·Materialization 포함), Workshop, AIP Logic, Automate, Object Views, Restricted view, TypeScript function 등. TS v2 function은 로컬 OSDK를 쓸 때만 브랜치에서 수정할 수 있습니다. Python function은 브랜치에서 수정할 수 없고 특정 버전을 참조해 테스트할 수만 있습니다(Main 스키마만 사용).",
      "Proposal이 PR 역할을 합니다. 리소스별 승인 → merge check → Merge 순서로 진행되며 일부만 실패한 병합은 되돌릴 수 없습니다.",
      "브랜치에서 리소스를 만들거나 지우면 Main에도 반영됩니다. Ontology 리소스는 예외로 브랜치에서 만들고 지워도 Main에 영향을 주지 않습니다.",
      "Branch protection은 리소스 owner가 켜거나 끕니다. 프로젝트의 Branch protection 탭에서 새 파일을 자동으로 보호하도록 설정할 수도 있습니다. Ontology 리소스는 먼저 project permissions로 migration해야 보호할 수 있습니다.",
      "기본값으로 35일 동안 쓰지 않은 브랜치는 비활성화되고 그 7일 뒤 브랜치 데이터가 삭제됩니다.",
    ],
    warn: "브랜치에서 Action으로 만든 편집은 테스트용이며 Main에 병합되지 않습니다. 일반 OSDK 앱은 브랜치를 지원하지 않고 Developer Console도 지원 대상에 없습니다. 예외는 TS v2 function의 로컬 OSDK와 pro-code agent(베타)의 OSDK 호출입니다. pro-code agent는 브랜치 컨텍스트를 물려받지만 스키마는 Main의 것을 씁니다.",
    doc: D + "global-branching/core-concepts",
    related: [
      { label: "지원 범위", href: D + "global-branching/integrations" },
      { label: "리소스 보호", href: D + "global-branching/resource-protection-and-approval-policies" },
      { label: "로컬 OSDK", href: D + "functions/local-sdks" },
      { label: "Agent 브랜치", href: D + "agents/branching" },
      { label: "GA 공지", href: D + "announcements/2026-05" },
      { label: "브랜치에서 Action 실행", href: D + "action-types/branching-action-types" },
      { label: "Ontology 브랜치", href: D + "ontologies/branching-ontology" },
    ],
  },
  {
    id: "market", short: "Marketplace", layer: "ops", title: "Marketplace · Foundry DevOps",
    lead: "리소스를 product로 묶어 버전을 관리하고 환경별로 설치합니다.",
    analogy: "npm 패키지처럼 리소스 묶음에 버전을 붙여 배포하고 개발·테스트·운영 환경마다 설치·업그레이드하는 구조입니다.",
    everyday: "만들어 둔 업무 도구 묶음을 앱스토어의 앱처럼 버전별로 올려 두고 부서(환경)마다 설치하고 업데이트하는 구조입니다.",
    points: [
      "Product는 Input(연결할 의존 리소스)과 Output(설치로 생성되는 리소스)으로 구성됩니다.",
      "Store는 product 모음입니다. 로컬 Store는 저장된 프로젝트나 폴더의 권한을 상속하고 원격 Store 권한은 Control Panel에서 설정합니다.",
      "개발·테스트·운영 환경별로 설치할 수 있습니다. release channel을 지정하면 그 채널의 새 버전이 업그레이드 후보로 표시될 뿐이며 자동으로 설치하려면 Automatic upgrades(베타)를 켜야 합니다. 자동 업그레이드는 기본으로 꺼져 있습니다.",
    ],
    doc: [
      { label: "Marketplace", href: D + "marketplace/overview" },
      { label: "Foundry DevOps", href: D + "devops/core-concepts" },
    ],
    related: [
      { label: "설치하기", href: D + "marketplace/install-product" },
      { label: "설치 설정", href: D + "marketplace/installations" },
      { label: "업그레이드", href: D + "marketplace/upgrades" },
      { label: "Store 권한", href: D + "foundry-devops/manage-store-permissions" },
      { label: "릴리스 관리", href: D + "devops-release-management/use-devops-for-release-management" },
    ],
  },
  {
    id: "lineage", short: "Data Lineage · Workflow Lineage", mapLines: ["Data Lineage", "Workflow Lineage"], layer: "ops", title: "Data Lineage · Workflow Lineage",
    lead: "Data Lineage는 데이터가 원천에서 Ontology를 거쳐 워크플로까지 흐르는 과정을 보여 주는 대화형 도구입니다. Workflow Lineage는 Ontology 위에 만든 앱과 그 아래 처리 과정을 이해하고 관리하는 작업 공간입니다.",
    analogy: "Data Lineage는 dbt docs의 lineage 그래프처럼 테이블이 어떤 작업을 거쳐 만들어지는지 보여 줍니다. Workflow Lineage는 IDE의 'Find usages'와 의존성 그래프를 합친 것과 비슷해서 컬럼 하나를 쓰는 Action과 화면을 끝까지 따라갈 수 있습니다.",
    everyday: "Data Lineage는 원재료가 어느 공정을 거쳐 제품이 되었는지 보여 주는 생산 이력표와 같습니다. Workflow Lineage는 매장에 놓인 상품(앱)이 어떤 부품과 양식으로 조립되었는지 보여 주는 조립도에 가깝습니다.",
    points: [
      "Data Lineage는 원천부터 Ontology와 워크플로까지 전 구간을 보여 주고 Workflow Lineage는 Ontology 위의 워크플로를 관리합니다. Workflow Lineage에서 Object type을 Data Lineage로 열면 그 Object type으로 들어오는 데이터의 Schedule을 확인할 수 있습니다.",
      "Data Lineage에서는 Schedule을 관리하고 Build timeline으로 Build 이력을 봅니다. Dataset을 이전 트랜잭션으로 롤백하는 곳도 Data Lineage입니다. 보관(archive)되었거나 비활성 상태인 브랜치에서는 Build가 자동으로 실패하므로 그 브랜치의 리소스를 Build하는 Schedule이 반복된 실패로 멈출 수 있습니다. 이때는 Build Schedules 앱이나 Data Lineage에서 다시 시작합니다.",
      "Workflow Lineage는 Object·Action·Function·Interface·Custom widget·앱의 API 이름·입력·Ontology 편집·Submission criteria를 보여 줍니다. Object의 특정 컬럼을 쓰는 하류 Action과 Workshop 앱을 모두 찾을 수 있습니다.",
      "Workflow Lineage에서는 권한·사용량·마지막 재인덱싱 상태를 색으로 보고 Action 버전 일괄 변경이나 Submission criteria 직접 수정 같은 작업도 합니다.",
      "둘 다 Global Branching을 지원합니다. 브랜치에서 리소스를 지우면 브랜치 상태가 깨질 수 있으므로 지우기 전에 lineage로 다른 브랜치 리소스가 그 리소스에 기대고 있지 않은지 확인해야 합니다.",
    ],
    warn: "Workflow Lineage에 누가 접근할지는 관리자가 Control Panel에서 정하며 환경(enrollment)에 따라 아직 켜져 있지 않을 수 있습니다.",
    doc: [
      { label: "Data Lineage", href: D + "data-lineage/overview" },
      { label: "Workflow Lineage", href: D + "workflow-lineage/overview" },
    ],
    related: [
      { label: "Schedule 관리", href: D + "data-lineage/manage-schedules" },
      { label: "Build timeline", href: D + "data-lineage/build-timeline" },
      { label: "롤백", href: D + "data-lineage/dataset-rollback" },
      { label: "브랜치 지원 범위", href: D + "global-branching/integrations" },
      { label: "브랜치에서 리소스 제거", href: D + "global-branching/core-concepts" },
    ],
  },
];
